dataset:
  repo_id: repo_smolvla
  root: /root/gpufree-data/lehome/Datasets/example/four_types_merged
  image_transforms:
    enable: true
    max_num_transforms: 1

policy:
  type: spgvla
  device: cuda
  push_to_hub: false
  pretrained_path: /root/gpufree-data/lehome/outputs/train/spgvla_exp14_pg_wm_bs_96_finetune_add_noise_0.05/checkpoints/030000/pretrained_model
  
  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
  
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: /root/gpufree-data/lehome/outputs/train/spgvla_exp16_pg_wm_bs_96_finetune_add_noise_0.08
batch_size: 96
steps: 30000
save_freq: 10000
log_freq: 100

wandb:
  enable: false